name: CI

defaults:
  run:
    shell: pwsh

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build, Publish, and Pack
        run: .\build.ps1 -Configuration Release -SkipTest -Pack

      - name: Upload NuGet Packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ./packages/*.nupkg

      - name: Upload Test Resources (AOT)
        uses: actions/upload-artifact@v4
        with:
          name: test-resource-aot
          path: tests/TestResource.Aot/bin/Release/**/publish/

      - name: Upload Test Resources (NonAot)
        uses: actions/upload-artifact@v4
        with:
          name: test-resource-nonaot
          path: tests/TestResource.NonAot/bin/Release/**/publish/

      - name: Upload Test Resources (Options)
        uses: actions/upload-artifact@v4
        with:
          name: test-resource-options
          path: tests/TestResource.Options/bin/Release/**/publish/

  test:
    needs: build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Download Test Resources (AOT)
        uses: actions/download-artifact@v4
        with:
          name: test-resource-aot
          path: tests/TestResource.Aot/bin/Release/net10.0/publish/

      - name: Download Test Resources (NonAot)
        uses: actions/download-artifact@v4
        with:
          name: test-resource-nonaot
          path: tests/TestResource.NonAot/bin/Release/net10.0/publish/

      - name: Download Test Resources (Options)
        uses: actions/download-artifact@v4
        with:
          name: test-resource-options
          path: tests/TestResource.Options/bin/Release/net10.0/publish/

      - name: Install Pester
        run: Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run Tests
        run: .\build.ps1 -InstallDsc -SkipBuild

  publish:
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - name: Download NuGet Packages
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: ./packages

      - name: Publish to NuGet
        run: |
          dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
